namespace Tibia.Connection {
    public enum IncomingPacketType : byte {

        #region "[rgn] Incoming "
        Unknow = 0x00,
        CharListLoginData = 0x01,
        AddCreature = 0x0A,
        BadLogin = 0x0A,
        CharList = 0x14,
        InformationBox = 0x15,
        Ping = 0x1E,
        MapItemAdd = 0x6A,
        MapItemUpdate = 0x6B,
        MapItemRemove = 0x6C,
        CreatureMove = 0x6D,
        ContainerOpened = 0x6E,
        ContainerClosed = 0x6F,
        ContainerItemAdd = 0x70,
        ContainerItemUpdate = 0x71,
        ContainerItemRemove = 0x72,
        EqItemAdd = 0x78,
        EqItemRemove = 0x79,
        TradeBoxOpen = 0x7A,
        WorldLight = 0x82,
        TileAnimation = 0x83,
        AnimatedText = 0x84,
        Projectile = 0x85,
        CreatureSquare = 0x86,
        CreatureHealth = 0x8C,
        CreatureLight = 0x8D,
        CreatureOutfit = 0x8E,
        CreatureSpeed = 0x8F,
        CreatureSkull = 0x90,
        PartyInvite = 0x91,
        BookOpen = 0x96,
        StatusUpdate = 0xA0,
        SkillUpdate = 0xA1,
        FlagUpdate = 0xA2,
        CancelTarget = 0xA3,
        ChatMessage = 0xAA,
        ChannelList = 0xAB,
        ChannelOpen = 0xAC,
        PrivateChannelOpen = 0xAD,
        StatusMessage = 0xB4,
        CancelAutoWalk = 0xB5,
        VipAdd = 0xD2,
        VipLogin = 0xD3,
        VipLogout = 0xD4,
        #endregion
    }

    public enum OutgoingPacketType : byte {
        #region "[rgn] Outgoing "
        Unknow = 0x00,
        Logout = 0x14,
        ItemMove = 0x78,
        ItemUse = 0x82,
        ItemUseOn = 0x83,
        ItemUseBattlelist = 0x84,
        ContainerClose = 0x87,
        ContainerOpenParent = 0x88,
        LookAt = 0x8C,
        PlayerSpeech = 0x96,
        ClientLoggedIn = 0xA0,
        Attack = 0xA1,
        CancelMove = 0xBE,
        #endregion
    }
}
